import * as GUI from 'babylonjs-gui';

// 水平对齐
export const HORIZONTALALIGNMENT = {
  HORIZONTAL_ALIGNMENT_RIGHT: GUI.Control.HORIZONTAL_ALIGNMENT_RIGHT, // 右
  HORIZONTAL_ALIGNMENT_LEFT: GUI.Control.HORIZONTAL_ALIGNMENT_LEFT, // 左
  HORIZONTAL_ALIGNMENT_CENTER: GUI.Control.HORIZONTAL_ALIGNMENT_CENTER, // 居中
};
// 垂直对齐
export const VERTICALALIGNMENT = {
  VERTICAL_ALIGNMENT_TOP: GUI.Control.VERTICAL_ALIGNMENT_TOP, // 顶部
  VERTICAL_ALIGNMENT_BOTTOM: GUI.Control.VERTICAL_ALIGNMENT_BOTTOM, // 底部
  VERTICAL_ALIGNMENT_CENTER: GUI.Control.VERTICAL_ALIGNMENT_CENTER, // 中心
};
// 动画状态
export const ANIMATIONSTATES = {
  PLAY: 'reset', // 播放的设置方式还有待商榷
  PAUSE: 'pause',
  RESTART: 'restart',
  STOP: 'stop',
  RESET: 'reset',
};
